# Application
quarkus.application.name=metriq
quarkus.http.port=38790

# Aivox bridge
metriq.aivox.url=http://localhost:38798
# Jesoos bridge
metriq.jesoos.url=http://localhost:38799

quarkus.index-dependency.core.group-id=io.kneo
quarkus.index-dependency.officeframe.group-id=io.kneo

# Logging
quarkus.log.level=INFO
quarkus.log.category."io.smallrye.reactive.messaging".level=DEBUG
quarkus.log.category."io.vertx.rabbitmq".level=DEBUG

# Scheduler
quarkus.scheduler.enabled=true

# Health Checks
quarkus.smallrye-health.enabled=true

# Optionally disable Dev UI entirely (comment out if you want Dev UI)
# quarkus.devui.enabled=false

# Suppress verbose FFmpeg wrapper output
quarkus.log.category."net.bramp.ffmpeg".level=WARN
quarkus.log.category."net.bramp.ffmpeg.builder".level=ERROR
quarkus.log.category."net.bramp.ffmpeg.RunProcessFunction".level=ERROR

