# Application
quarkus.package.jar.type=uber-jar
quarkus.application.name=metriq
quarkus.http.port=38790

quarkus.index-dependency.core.group-id=io.kneo
quarkus.index-dependency.officeframe.group-id=io.kneo
quarkus.arc.exclude-types=com.semantyca.core.jwt.JWTCallerPrincipalFactory,io.smallrye.jwt.auth.cdi.JWTCallerPrincipalFactoryProducer

# Logging
quarkus.log.level=INFO
quarkus.log.category."io.smallrye.reactive.messaging".level=DEBUG
quarkus.log.category."io.vertx.rabbitmq".level=DEBUG

# Scheduler
quarkus.scheduler.enabled=true
quarkus.scheduler.start-mode=forced

# Health Checks
quarkus.smallrye-health.enabled=true

# Optionally disable Dev UI entirely (comment out if you want Dev UI)
# quarkus.devui.enabled=false

